### ISSUE TITLE
install client correctly

### ISSUE THREAD

**Issue by kzidane** [cs50/help50-server#2]
update https://github.com/cs50/help50-server/blob/master/Dockerfile#L5 once cs50/help50-client is ready.

**Comment by dmalan** [comment]
And should also include an `apt-get install help50` probably, after adding our PPA!

**Comment by kzidane** [comment]
Hm, was actually thinking about cloning the repo and manually installing, since we might want to work with the latest dev version?

**Comment by dmalan** [comment]
Sure, that works. Maybe just put in `/usr/local/bin` then to make clear to us it's a local install.
