### ISSUE TITLE
Catch runtime error for out of bounds array access

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/help50-server#20]
Example:
Declare a char array: `char cipher[strlen(p)];`  and then later, try to set `cipher[strlen(p)] = '\0'` which is one past the end of the array.
error: `vigenere.c:56:17: runtime error: index 2 out of bounds for type 'char [strlen(p)]'`

**Comment by brianyu28** [comment]
Actually, this is already handled by the server.

https://github.com/cs50/help50-server/blob/master/helpers/clang.py#L28
https://github.com/cs50/help50-server/blob/master/helpers/clang.py#L548
